#企业微信应用通知参数配置
#下方填入企业微信应用以及plex相关的参数,xxxxx就是需要自己填的，appcode按需修改
#企业微信应用消息官方文档可参考：https://developer.work.weixin.qq.com/document/path/90854#%E5%9B%BE%E6%96%87%E6%B6%88%E6%81%AF
wxapp:
  corpid: xxxxxx   #企业ID 
  secret: xxxxxx   #企业应用的密钥
  agentid: xxxxxx  #应用ID 通常是 1000008 这样的格式
  touser: xxxxxx   #接收通知的账号: 进入企微后台-应用管理-点用于发通知的应用-鼠标悬停在管理员的小卡片-弹出小弹窗中的账号就是需要填这里的，特殊情况填@all,所有人都可收到通知。
  type: news       #可选消息类型 news(图文消息) textcard(卡片消息，不展示影片海报图) text(纯文本)
  plex_server_url: https://xxxxxx.com:32400     #外网 plex 服务器地址，能外网访问的域名地址，非443端口记得加。若填内网地址，推送图片只在内网才能查看到，外网时图片无法显示
  picurl_default: https://xxxxxx.a.png   #通知缺省背景图，当没有获取到背景封面时调用此图
  plex_token: xxxxxx     #plex身份认证，否则无法获取封面背景图，获取方式：在plex中随意点开一部影片封面右下角3个点，然后选择获取信息，再点弹窗左下角的查看xml会跳转链接,查看浏览器地址栏有X-Plex-Token字样
  #配置正确的appcode可展示客户端ip归属地。该值为空则不展示。appcode获取方法（显示归属地其实没什么用，保持为空即可。如果一定要用，下面是方法）：在阿里云市场购买的1元含2万5千次请求，或者试用用免费的 https://reurl.cc/W103r5 进入管理控制台，在已购买的服务中可以找到AppCode
  appcode: ''
